pip install streamlit yfinance pandas matplotlib
streamlit run app.py
import streamlit as st
import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from datetime import datetime, timedelta
import io

# --- Page Configuration ---
st.set_page_config(
    page_title="DarkPool Titan Newsletter",
    page_icon="🫟",
    layout="wide"
)

# --- Custom CSS for DarkPool Theme ---
st.markdown("""
    <style>
    .main {
        background-color: #0e1117;
        color: #e0e0e0;
    }
    .stMetric {
        background-color: #1f2937;
        padding: 10px;
        border-radius: 5px;
        border: 1px solid #374151;
    }
    h1, h2, h3 {
        color: #4ade80 !important; /* Matrix Green/Titan Green */
        font-family: 'Helvetica Neue', sans-serif;
    }
    .report-text {
        font-family: 'Georgia', serif;
        line-height: 1.6;
    }
    </style>
    """, unsafe_allow_html=True)

# --- Helper Functions ---

def get_market_data():
    """Fetches real-time 7-day percent change for key assets."""
    tickers = {
        "BITCOIN": "BTC-USD",
        "ETHEREUM": "ETH-USD",
        "GOLD": "GC=F",
        "NASDAQ": "NQ=F",
        "S&P500": "ES=F",
        "FTSE 100": "^FTSE",
        "AUS 200": "^AXJO" 
    }
    
    data_summary = {}
    
    for name, ticker in tickers.items():
        try:
            # Fetch 1 month of data to ensure we get a clean 7-day delta
            hist = yf.Ticker(ticker).history(period="1mo")
            if len(hist) >= 7:
                current = hist['Close'].iloc[-1]
                seven_days_ago = hist['Close'].iloc[-7]
                change_pct = ((current - seven_days_ago) / seven_days_ago) * 100
                data_summary[name] = change_pct
            else:
                data_summary[name] = 0.0
        except Exception as e:
            data_summary[name] = 0.0
            
    return data_summary

def create_summary_image(market_data, headlines, date_str):
    """Generates a summary infographic using Matplotlib."""
    
    # Setup Figure
    fig, ax = plt.subplots(figsize=(12, 8))
    fig.patch.set_facecolor('#0e1117')
    ax.set_facecolor('#0e1117')
    
    # Title Area
    plt.text(0.5, 0.95, "DARKPOOL TITAN", color='white', fontsize=30, weight='bold', ha='center', fontname='Arial')
    plt.text(0.5, 0.90, f"WEEKLY MARKET SUMMARY | {date_str}", color='#4ade80', fontsize=14, ha='center', fontname='Arial')
    
    # Draw Market Boxes
    y_pos = 0.75
    x_start = 0.05
    box_width = 0.12
    gap = 0.01
    
    for i, (asset, change) in enumerate(market_data.items()):
        color = '#22c55e' if change >= 0 else '#ef4444' # Green or Red
        rect = patches.FancyBboxPatch((x_start + (i * (box_width + gap)), y_pos), box_width, 0.1, 
                                     boxstyle="round,pad=0.02", linewidth=1, edgecolor=color, facecolor='#1f2937')
        ax.add_patch(rect)
        
        # Asset Name
        plt.text(x_start + (i * (box_width + gap)) + box_width/2, y_pos + 0.07, asset, 
                 color='white', fontsize=9, ha='center', weight='bold')
        
        # Percent Change
        sign = "+" if change > 0 else ""
        plt.text(x_start + (i * (box_width + gap)) + box_width/2, y_pos + 0.03, f"{sign}{change:.1f}%", 
                 color=color, fontsize=14, ha='center', weight='bold')

    # Headlines Section
    plt.text(0.05, 0.65, "KEY MARKET EVENTS & INSIGHTS", color='#4ade80', fontsize=18, weight='bold')
    
    y_text = 0.58
    for headline in headlines:
        plt.text(0.05, y_text, f"• {headline}", color='white', fontsize=12, wrap=True)
        y_text -= 0.08

    # Footer/Branding
    plt.text(0.5, 0.05, "Generated by DarkPool Titan App", color='#6b7280', fontsize=10, ha='center', style='italic')

    ax.axis('off')
    
    # Save to BytesIO object
    buf = io.BytesIO()
    plt.savefig(buf, format='png', dpi=100, bbox_inches='tight', facecolor=fig.get_facecolor())
    buf.seek(0)
    return buf

# --- Main App Interface ---

def main():
    # Sidebar for Inputs
    st.sidebar.title("Newsletter Configuration")
    report_date = st.sidebar.date_input("Report Date", datetime.now())
    
    st.sidebar.subheader("Headlines (for Image)")
    hl1 = st.sidebar.text_input("Headline 1", "Dovish Kevin Hasset frontrunner for Fed Chair")
    hl2 = st.sidebar.text_input("Headline 2", "Santa Rally Odds Look Favorable")
    hl3 = st.sidebar.text_input("Headline 3", "Bitcoin Sentiment Hits 'Extreme Fear'")
    headlines = [hl1, hl2, hl3]

    # --- Header ---
    st.title("🫟 DarkPool Titan Weekly Newsletter")
    st.write(f"**Date:** {report_date.strftime('%B %d, %Y')}")
    st.markdown("---")

    # --- Section 1: Weekly Market Summary (Live Data) ---
    st.subheader("WEEKLY MARKET SUMMARY (Live Data)")
    
    with st.spinner("Fetching latest market data..."):
        market_data = get_market_data()
    
    # Display Metrics in Columns
    cols = st.columns(len(market_data))
    for i, (asset, change) in enumerate(market_data.items()):
        color = "normal" 
        # Streamlit metric delta color logic
        with cols[i]:
            st.metric(label=asset, value=f"{change:.1f}%", delta=f"{change:.1f}%")

    st.markdown("---")

    # --- Section 2: Report Content Generator ---
    
    col1, col2 = st.columns([2, 1])
    
    with col1:
        st.subheader("📝 Report Editor")
        
        # General Market Update
        st.markdown("### 🌍 Macro & Sentiment")
        macro_text = st.text_area("Market Context", height=200, value="""Judging from recent news, traders and investors have many reasons to be optimistic: 
- Dovish former White House economic adviser Kevin Hasset is the overwhelming frontrunner to replace Jerome Powell.
- The odds of having a Santa Rally this year look favorable.
- 85%+ probability of a 25 basis point cut by the Fed next week.

Despite these headlines, sentiment remains low. The CNN Fear & Greed Index remains in fear.""")

        # Bitcoin Update
        st.markdown("### ₿ Bitcoin Update")
        btc_text = st.text_area("Crypto Analysis", height=200, value="""Bitcoin Update: Good news is bad news.
In stocks, good news still lifts prices. In Bitcoin, good news barely moves the needle anymore.
Sentiment has plunged to extreme fear, levels lower than during the FTX collapse.

Support 1: $81K
Resistance 1: $93K""")

        # Real Estate Update
        st.markdown("### 🏠 Real Estate / Sectors")
        re_text = st.text_area("Real Estate Analysis", height=150, value="""Governments are racing to build new homes, yet the units already sitting there have rarely been so empty.
One clear example is Melbourne, Australia, with the number of empty units back above 100,000.""")

    with col2:
        st.subheader("📅 Significant Events (Upcoming)")
        # In a real production app, we could scrape this. 
        # For now, we allow the user to input critical upcoming dates.
        event_1 = st.text_input("Event 1", "FOMC Meeting (Next Week)")
        event_2 = st.text_input("Event 2", "CPI Data Release (Thursday)")
        event_3 = st.text_input("Event 3", "NVDA Earnings (Wednesday)")
        
        st.subheader("📊 Options & Earnings Data")
        earnings_list = st.text_area("Earnings Watchlist", "ADBE, COST, AVGO")
        options_note = st.text_area("Options Flows", "High call volume on IWM. BTC puts stacking at $85k.")

    st.markdown("---")

    # --- Section 3: Visualization & Export ---
    st.subheader("🖼️ Generate Newsletter Assets")
    
    if st.button("Generate Summary Image"):
        image_buf = create_summary_image(market_data, headlines, report_date.strftime('%B %d, %Y'))
        st.image(image_buf, caption="Generated Newsletter Header", use_container_width=True)
        
        st.download_button(
            label="Download Image",
            data=image_buf,
            file_name="darkpool_weekly_summary.png",
            mime="image/png"
        )

    # Preview Full Text
    with st.expander("Preview Full Email Text"):
        full_email = f"""
Subject: 🫟 DarkPool Titan Weekly: {headlines[0]}

WEEKLY MARKET SUMMARY
{', '.join([f"{k}: {v:+.1f}%" for k,v in market_data.items()])}

Hi Traders,

{macro_text}

---
BITCOIN UPDATE
{btc_text}

---
REAL ESTATE & SECTORS
{re_text}

---
UPCOMING EVENTS
- {event_1}
- {event_2}
- {event_3}

To your trading success,
The DarkPool Titan Team
        """
        st.code(full_email, language="text")

if __name__ == "__main__":
    main()
